export let data = [
    {
      id: 1,
      Timer: "1.40",
      balance: 100,
      description: "Зарегистрироваться на сайте",
      link: "",
      timer: 10,
      price: 20,
    },
    {
      id: 11,
      Timer: "2.23",
      description: "Поставить лайк и оставить коментарии",
      link: "",
      balance: 100,
      timer: 10,
      price: 10,
    },
    {
      id: 3,
      Timer: "0.99",
      description: "Зарегистрироваться на сайте",
      link: "",
      balance: 100,
      timer: 10,
      price: 25,
    },
    {
      id: 4,
      Timer: "1.59",
      description: "Поставить лайк и оставить коментарии",
      link: "",
      balance: 100,
      timer: 10,
      price: 15,
    },
    {
      id: 5,
      Timer: "0.66",
      description: "Зарегистрироваться на сайте",
      link: "",
      balance: 100,
      timer: 10,
      price: 5,
    },
];

